### ISSUE TITLE
Remove this repository

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/docs#5]
@EvanLovely @bradfrost what is this repo for ? It's existence is causing confusion: https://github.com/pattern-lab/edition-node-gulp/issues/120

The website repo is where our docs reside

**Comment by bradfrost** [comment]
Looks like @EvanLovely owns this. I'm all on board to remove it, but will leave that up to Evan since he likely knows what's up.

**Comment by EvanLovely** [comment]
Good call! Deleting...
